#!/usr/bin/env bash

#Author	    :	thebinary <binary4bytes@gmail.com>
#Date	    :	Tue Jun 11 01:50:06 +0545 2019-06-11
#Purpose    :	Example Table definition for this sdk, for IF-MIB

S_ROOT_IFMIB=".1.3.6.1.2.1.2.2.1"
S_FIELD_IFMIB_INDEX="i 1"
S_FIELD_IFMIB_DESCR="s 2"
S_FIELD_IFMIB_TYPE="i 3"
S_FIELD_IFMIB_MTU="i 4"
S_FIELD_IFMIB_SPEED="i 5"
S_FIELD_IFMIB_PHYSADDRESS="s 6"
S_FIELD_IFMIB_ADMINSTATUS="i 7"
S_FIELD_IFMIB_OPERSTATUS="i 8"
S_FIELD_IFMIB_INOCTETS="i 10"
S_FIELD_IFMIB_INUCASTPKTS="i 11"
S_FIELD_IFMIB_INNUCASTPKTS="i 12"
S_FIELD_IFMIB_INDISCARDS="i 13"
S_FIELD_IFMIB_INERRORS="i 14"
S_FIELD_IFMIB_INUNKNOWNPROTOS="i 15"
S_FIELD_IFMIB_OUTOCTETS="i 16"
S_FIELD_IFMIB_OUTUCASTPKTS="i 17"
S_FIELD_IFMIB_OUTNUCASTPKTS="i 18"
S_FIELD_IFMIB_OUTDISCARDS="i 19"
S_FIELD_IFMIB_OUTERRORS="i 20"
